sudo: false
language: python
python:
  - 3.5
before_install:
  - "nvm install stable"
install:
  - "pip install -r test_requirements.txt"
  - "npm install"
before_script:
  - "gulp build"
env:
  - SCRIPT="gulp test"
  - SCRIPT="python src/py/tests.py"
  - SCRIPT="SELENIUM_WEBDRIVER=PhantomJS SELENIUM_DEBUG=1 python src/html/tests.py"
script:
  - "$SCRIPT"
